// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FCT.CookieBakerRT.IPC_DataFormat
{

using global::System;
using global::FlatBuffers;


import javax.annotation.Nullable;
public struct AABB_Bounds : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public AABB_Bounds __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FCT.CookieBakerRT.IPC_DataFormat.Vec3 Center { get { return (new FCT.CookieBakerRT.IPC_DataFormat.Vec3()).__assign(__p.bb_pos + 0, __p.bb); } }
  public FCT.CookieBakerRT.IPC_DataFormat.Vec3 Extent { get { return (new FCT.CookieBakerRT.IPC_DataFormat.Vec3()).__assign(__p.bb_pos + 12, __p.bb); } }

  public static Offset<FCT.CookieBakerRT.IPC_DataFormat.AABB_Bounds> CreateAABB_Bounds(FlatBufferBuilder builder, float Center_X, float Center_Y, float Center_Z, float Extent_X, float Extent_Y, float Extent_Z) {
    builder.Prep(4, 24);
    builder.Prep(4, 12);
    builder.PutFloat(Extent_Z);
    builder.PutFloat(Extent_Y);
    builder.PutFloat(Extent_X);
    builder.Prep(4, 12);
    builder.PutFloat(Center_Z);
    builder.PutFloat(Center_Y);
    builder.PutFloat(Center_X);
    return new Offset<FCT.CookieBakerRT.IPC_DataFormat.AABB_Bounds>(builder.Offset);
  }
};


}
