// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FCT.CookieBakerRT.IPC_DataFormat
{

using global::System;
using global::FlatBuffers;

public struct MeshObject : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public MeshObject __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FCT.CookieBakerRT.IPC_DataFormat.Matrix4x4 LocalToWorldMatrix { get { return (new FCT.CookieBakerRT.IPC_DataFormat.Matrix4x4()).__assign(__p.bb_pos + 0, __p.bb); } }
  public int IndicesOffset { get { return __p.bb.GetInt(__p.bb_pos + 64); } }
  public int IndicesCount { get { return __p.bb.GetInt(__p.bb_pos + 68); } }
  public int VerticesOffset { get { return __p.bb.GetInt(__p.bb_pos + 72); } }
  public FCT.CookieBakerRT.IPC_DataFormat.AABB_Bounds Bounds { get { return (new FCT.CookieBakerRT.IPC_DataFormat.AABB_Bounds()).__assign(__p.bb_pos + 76, __p.bb); } }

  public static Offset<FCT.CookieBakerRT.IPC_DataFormat.MeshObject> CreateMeshObject(FlatBufferBuilder builder, float LocalToWorldMatrix_M11, float LocalToWorldMatrix_M12, float LocalToWorldMatrix_M13, float LocalToWorldMatrix_M14, float LocalToWorldMatrix_M21, float LocalToWorldMatrix_M22, float LocalToWorldMatrix_M23, float LocalToWorldMatrix_M24, float LocalToWorldMatrix_M31, float LocalToWorldMatrix_M32, float LocalToWorldMatrix_M33, float LocalToWorldMatrix_M34, float LocalToWorldMatrix_M41, float LocalToWorldMatrix_M42, float LocalToWorldMatrix_M43, float LocalToWorldMatrix_M44, int IndicesOffset, int IndicesCount, int VerticesOffset, float Bounds_Center_X, float Bounds_Center_Y, float Bounds_Center_Z, float Bounds_Extent_X, float Bounds_Extent_Y, float Bounds_Extent_Z) {
    builder.Prep(4, 100);
    builder.Prep(4, 24);
    builder.Prep(4, 12);
    builder.PutFloat(Bounds_Extent_Z);
    builder.PutFloat(Bounds_Extent_Y);
    builder.PutFloat(Bounds_Extent_X);
    builder.Prep(4, 12);
    builder.PutFloat(Bounds_Center_Z);
    builder.PutFloat(Bounds_Center_Y);
    builder.PutFloat(Bounds_Center_X);
    builder.PutInt(VerticesOffset);
    builder.PutInt(IndicesCount);
    builder.PutInt(IndicesOffset);
    builder.Prep(4, 64);
    builder.PutFloat(LocalToWorldMatrix_M44);
    builder.PutFloat(LocalToWorldMatrix_M43);
    builder.PutFloat(LocalToWorldMatrix_M42);
    builder.PutFloat(LocalToWorldMatrix_M41);
    builder.PutFloat(LocalToWorldMatrix_M34);
    builder.PutFloat(LocalToWorldMatrix_M33);
    builder.PutFloat(LocalToWorldMatrix_M32);
    builder.PutFloat(LocalToWorldMatrix_M31);
    builder.PutFloat(LocalToWorldMatrix_M24);
    builder.PutFloat(LocalToWorldMatrix_M23);
    builder.PutFloat(LocalToWorldMatrix_M22);
    builder.PutFloat(LocalToWorldMatrix_M21);
    builder.PutFloat(LocalToWorldMatrix_M14);
    builder.PutFloat(LocalToWorldMatrix_M13);
    builder.PutFloat(LocalToWorldMatrix_M12);
    builder.PutFloat(LocalToWorldMatrix_M11);
    return new Offset<FCT.CookieBakerRT.IPC_DataFormat.MeshObject>(builder.Offset);
  }
};


}
