// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FCT.CookieBakerRT.IPC_DataFormat
{

public enum MessageDatum : byte
{
  NONE = 0,
  UpAndRunning = 1,
  WorkloadRequest = 2,
  WorkloadReceived = 3,
  ProgressUpdate = 4,
  WorkloadComplete = 5,
  CancelWorkload = 6,
  ShutdownMessage = 7,
};


}
