// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FCT.CookieBakerRT.IPC_DataFormat
{

using global::System;
using global::FlatBuffers;

public struct CancelWorkload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static CancelWorkload GetRootAsCancelWorkload(ByteBuffer _bb) { return GetRootAsCancelWorkload(_bb, new CancelWorkload()); }
  public static CancelWorkload GetRootAsCancelWorkload(ByteBuffer _bb, CancelWorkload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CancelWorkload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int WorkloadID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<FCT.CookieBakerRT.IPC_DataFormat.CancelWorkload> CreateCancelWorkload(FlatBufferBuilder builder,
      int WorkloadID = 0) {
    builder.StartTable(1);
    CancelWorkload.AddWorkloadID(builder, WorkloadID);
    return CancelWorkload.EndCancelWorkload(builder);
  }

  public static void StartCancelWorkload(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddWorkloadID(FlatBufferBuilder builder, int WorkloadID) { builder.AddInt(0, WorkloadID, 0); }
  public static Offset<FCT.CookieBakerRT.IPC_DataFormat.CancelWorkload> EndCancelWorkload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FCT.CookieBakerRT.IPC_DataFormat.CancelWorkload>(o);
  }
};


}
